# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Oulu Startup Ecosystem
tagline:          'Oulu Startup Ecosystem'
description:      'This is the central hub of Oulu Startup Ecosystem'
url:              http://oulustartup.github.io
baseurl:          /

author:
  name:           'Tuomas Jomppanen'
  url:            https://twitter.com/tuomasj

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/oulustartup/oulustartup.github.io
